# Following will define location of Reports Resources
MycologyWorksheetProvider=org.openelisglobal.common.provider.reports.MycologyWorksheetProvider
#AIS- LAB RESULTS
ResultsReportProvider=org.openelisglobal.common.provider.reports.ResultsReportProvider
